### ISSUE TITLE
Vue 2.0

### ISSUE THREAD

**Issue by rockymontana** [miaolz123/vue-chart#4]
Hello.
I've played around a bit to make your package fit with Vue 2.0..
Could you create a branch that I could PR to?
I guess you still want to support 1.0 so PRing to the master branch seems meaningless :-)

**Comment by beeplin** [comment]
+1

**Comment by miaolz123** [comment]
@rockymontana @beeplin Pls check it and thx~~

**Comment by rockymontana** [comment]
The PR is now merged into master, but maybe that's correct?

**Comment by beeplin** [comment]
I just tested the new version. It runs OK under vue2.0's stand-alone mode, but not run-time mode. the run-time mode only supports render functions, not < template >, unless we use vue-loader(in `.vue` format) to precompile `.vue` files into render functions via webpack.

So my suggestion is to provide an option for vue2 and vue-loader users:  not to export the webpack-processed  `dist/vue-chart.common.js`, but to export the original `.vue` file.

# 

Here is something from vue2.0's docs:

Standalone vs. Runtime-only Build

There are two builds available, the standalone build and the runtime-only build.

The standalone build includes the compiler and supports the template option. It also relies on the presence of browser APIs so you cannot use it for server-side rendering.

The runtime-only build does not include the template compiler, and does not support the template option. You can only use the render option when using the runtime-only build, but it works with single-file components, because single-file components’ templates are pre-compiled into render functions during the build step. The runtime-only build is roughly 30% lighter-weight than the standalone build, weighing only 16kb min+gzip.

**Comment by rockymontana** [comment]
That sounds like a good solution.
Sorry that I missed that. I use it in stand alone mode... And only uses the component in .vue-files. Totally missed the other use-cases...

Jonas

**Comment by miaolz123** [comment]
@rockymontana 

> The PR is now merged into master, but maybe that's correct?

yeah, this point is also my confusion and just did this because:
- there are just a few words changed in the latest update
- npmjs.org take over version control

These are just my personal views~~

**Comment by miaolz123** [comment]
@beeplin good idea
